version: '3'

services:
  api:
    build: .
    restart: always
    command: ./wait-for-it.sh
    environment:
      DATABASE_NAME: estates
      DATABASE_USERNAME: jovalo
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: mypass
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - 'postgres'
  postgres:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: jovalo
      POSTGRES_DB: estates
      POSTGRES_PASSWORD: mypass

      